### ISSUE TITLE
`(exit #f)` do not make program fail

### ISSUE THREAD

**Issue by okuoku** [racket/r6rs#9]
Running following R6RS script do not make program fail.

```scheme
#!r6rs

(import (rnrs))

(exit #f)
```

```
$ plt-r6rs check.sps && echo SUCCESS
SUCCESS
```

On R6RS spec, `(exit #f)` needs to be considered as abnormal-exit 

- https://docs.racket-lang.org/r6rs/r6rs-lib-std/r6rs-lib-Z-H-11.html#node_idx_846

>  If obj is `#f`, the exit is assumed to be abnormal. 

Tested at:

- Racket: https://github.com/racket/racket/tree/4cf2b2c20fbd3829e6d35ce55f744590bad322a9
- R6RS: https://github.com/racket/r6rs/tree/f4d66a2c31749e3795722092b0a9d4fa698c2992

**Comment by soegaard** [comment]
If I am reading the code correctly, the R6RS version of `exit` is defined here:

https://github.com/racket/r6rs/blob/f27fb987f6e9268ce28892d269eb21b5a66677f8/r6rs-lib/rnrs/programs-6.rkt

The standard Racket `exit` is simply used. It will call the current exit handler, which work like this:

> The default [exit handler](https://docs.racket-lang.org/reference/Exiting.html#%28tech._exit._handler%29) in the Racket executable takes any argument, calls [plumber-flush-all](https://docs.racket-lang.org/reference/plumbers.html#%28def._%28%28quote._~23~25kernel%29._plumber-flush-all%29%29) on the original plumber, and shuts down the OS-level Racket process. The argument is used as the OS-level exit code if it is an exact integer between 1 and 255 (which normally means “failure”); otherwise, the exit code is 0, (which normally means “success”).

The default exit handler uses 1 to indicate a "failure", so the r6rs version of `exit` needs to be:

```
(define r6rs-exit
   (case-lambda 
     [()    (exit 0)]
     [(x)  (if x (exit x) (exit 1)]))

```
